/**
 * questionBank.js — PrepMatrix Assessment Question Pool
 * 80+ questions across 4 rounds: Aptitude, Technical, HR, Coding
 * Each question has: id, question, options[], correct (0-indexed), explanation, difficulty
 */

export const QUESTION_BANK = {

  /* ══════════════════════════════════════════════
     ROUND 1: APTITUDE
  ══════════════════════════════════════════════ */
  aptitude: [
    {
      id: 'apt_01',
      question: 'A train 150m long passes a pole in 15 seconds. How long will it take to pass a platform 300m long?',
      options: ['30 seconds', '45 seconds', '25 seconds', '40 seconds'],
      correct: 1,
      explanation: 'Speed = 150/15 = 10 m/s. Distance = 150+300 = 450m. Time = 450/10 = 45 seconds.',
      difficulty: 'medium',
    },
    {
      id: 'apt_02',
      question: 'If 20% of a number is 40, what is 30% of that number?',
      options: ['50', '55', '60', '65'],
      correct: 2,
      explanation: '20% = 40 → number = 200. 30% of 200 = 60.',
      difficulty: 'easy',
    },
    {
      id: 'apt_03',
      question: 'Find the next number in the series: 2, 6, 12, 20, 30, __',
      options: ['40', '42', '44', '48'],
      correct: 1,
      explanation: 'Pattern: n(n+1). 1×2=2, 2×3=6, 3×4=12, 4×5=20, 5×6=30, 6×7=42.',
      difficulty: 'medium',
    },
    {
      id: 'apt_04',
      question: 'A shopkeeper sells an item for ₹480 after giving a 20% discount. What was the marked price?',
      options: ['₹560', '₹580', '₹600', '₹620'],
      correct: 2,
      explanation: 'MP × (1 - 0.20) = 480 → MP = 480/0.80 = ₹600.',
      difficulty: 'easy',
    },
    {
      id: 'apt_05',
      question: 'Two pipes can fill a tank in 12 and 15 minutes respectively. If both are opened together, in how many minutes will the tank be full?',
      options: ['6.67 min', '8.50 min', '9 min', '7 min'],
      correct: 0,
      explanation: 'Combined rate = 1/12 + 1/15 = 5/60 + 4/60 = 9/60. Time = 60/9 ≈ 6.67 min.',
      difficulty: 'medium',
    },
    {
      id: 'apt_06',
      question: 'The average of 5 numbers is 27. If one number is excluded, the average becomes 25. What is the excluded number?',
      options: ['35', '30', '40', '45'],
      correct: 0,
      explanation: 'Sum of 5 = 135. Sum of 4 = 100. Excluded = 135 - 100 = 35.',
      difficulty: 'easy',
    },
    {
      id: 'apt_07',
      question: 'A car travels from A to B at 60 km/h and returns at 40 km/h. What is the average speed for the entire journey?',
      options: ['50 km/h', '48 km/h', '52 km/h', '46 km/h'],
      correct: 1,
      explanation: 'Average speed = 2ab/(a+b) = 2×60×40/(60+40) = 4800/100 = 48 km/h.',
      difficulty: 'medium',
    },
    {
      id: 'apt_08',
      question: 'In how many ways can the letters of the word "MATRIX" be arranged?',
      options: ['360', '480', '720', '600'],
      correct: 2,
      explanation: '"MATRIX" has 6 distinct letters. Arrangements = 6! = 720.',
      difficulty: 'medium',
    },
    {
      id: 'apt_09',
      question: 'If BOAT is coded as 2-15-1-20, how is EXAM coded?',
      options: ['5-24-1-13', '5-23-1-12', '4-24-1-13', '5-24-2-13'],
      correct: 0,
      explanation: 'A=1, B=2... E=5, X=24, A=1, M=13. So EXAM = 5-24-1-13.',
      difficulty: 'easy',
    },
    {
      id: 'apt_10',
      question: 'A and B can complete a work in 20 days. B and C can do it in 30 days. A and C can do it in 24 days. How many days will A alone take?',
      options: ['40 days', '48 days', '60 days', '30 days'],
      correct: 0,
      explanation: '2(A+B+C) = 1/20+1/30+1/24 = 6+4+5/120=15/120=1/8. A+B+C=1/16. A=1/16-1/30=30-16/480=14/480=7/240 ...A alone=240/6=40.',
      difficulty: 'hard',
    },
    {
      id: 'apt_11',
      question: 'The probability of getting a head in a single toss of a fair coin is:',
      options: ['1/4', '1/2', '1/3', '2/3'],
      correct: 1,
      explanation: 'A fair coin has 2 equally likely outcomes: H or T. P(H) = 1/2.',
      difficulty: 'easy',
    },
    {
      id: 'apt_12',
      question: 'What is the compound interest on ₹8000 at 10% per annum for 2 years?',
      options: ['₹1600', '₹1680', '₹1700', '₹1760'],
      correct: 1,
      explanation: 'CI = P(1+r)^n - P = 8000(1.1)^2 - 8000 = 9680 - 8000 = ₹1680.',
      difficulty: 'medium',
    },
    {
      id: 'apt_13',
      question: 'Find the odd one out: 2, 3, 5, 7, 11, 12, 13',
      options: ['11', '12', '13', '7'],
      correct: 1,
      explanation: 'All others are prime numbers. 12 = 2×6 is not prime.',
      difficulty: 'easy',
    },
    {
      id: 'apt_14',
      question: 'A clock shows 3:15. What is the angle between the hour and minute hands?',
      options: ['7.5°', '0°', '15°', '22.5°'],
      correct: 0,
      explanation: 'Minute hand at 90°. Hour hand at 3×30 + 15×0.5 = 90+7.5 = 97.5°. Angle = 97.5-90 = 7.5°.',
      difficulty: 'hard',
    },
    {
      id: 'apt_15',
      question: 'If the ratio of A:B = 3:4 and B:C = 2:5, find A:B:C.',
      options: ['3:4:10', '6:8:20', '3:4:5', '6:8:10'],
      correct: 1,
      explanation: 'A:B = 3:4. B:C = 2:5. Multiply: A:B:C = 3×2 : 4×2 : 4×5 = 6:8:20.',
      difficulty: 'medium',
    },
    {
      id: 'apt_16',
      question: 'In a group of 70, 40 like cricket, 30 like football. 15 like both. How many like neither?',
      options: ['10', '15', '20', '25'],
      correct: 1,
      explanation: 'n(C∪F) = 40+30-15 = 55. Neither = 70-55 = 15.',
      difficulty: 'medium',
    },
    {
      id: 'apt_17',
      question: 'A number is increased by 20% and then decreased by 20%. The net change is:',
      options: ['No change', '4% decrease', '4% increase', '2% decrease'],
      correct: 1,
      explanation: '100 → 120 → 120×0.80 = 96. Net change = -4%.',
      difficulty: 'easy',
    },
    {
      id: 'apt_18',
      question: 'Which of the following is divisible by both 4 and 6?',
      options: ['26', '34', '48', '52'],
      correct: 2,
      explanation: 'LCM(4,6) = 12. Among options, 48 is divisible by 12.',
      difficulty: 'easy',
    },
    {
      id: 'apt_19',
      question: 'A box contains 4 red and 3 blue balls. What is the probability of drawing a red ball?',
      options: ['3/7', '4/7', '4/3', '1/2'],
      correct: 1,
      explanation: 'P(Red) = 4/(4+3) = 4/7.',
      difficulty: 'easy',
    },
    {
      id: 'apt_20',
      question: 'What value replaces the ? in the pattern: 1, 4, 9, 16, 25, ?',
      options: ['30', '35', '36', '49'],
      correct: 2,
      explanation: 'Pattern: n². 1²=1, 2²=4, 3²=9, 4²=16, 5²=25, 6²=36.',
      difficulty: 'easy',
    },
  ],

  /* ══════════════════════════════════════════════
     ROUND 2: TECHNICAL (CS/DS/Algo)
  ══════════════════════════════════════════════ */
  technical: [
    {
      id: 'tech_01',
      question: 'What is the time complexity of Binary Search?',
      options: ['O(n)', 'O(n²)', 'O(log n)', 'O(n log n)'],
      correct: 2,
      explanation: 'Binary search halves the search space every iteration, giving O(log n) complexity.',
      difficulty: 'easy',
    },
    {
      id: 'tech_02',
      question: 'Which data structure uses LIFO (Last In First Out) ordering?',
      options: ['Queue', 'Stack', 'Linked List', 'Tree'],
      correct: 1,
      explanation: 'A Stack follows LIFO — the last element inserted is the first to be removed.',
      difficulty: 'easy',
    },
    {
      id: 'tech_03',
      question: 'What is the worst-case time complexity of Quicksort?',
      options: ['O(n log n)', 'O(n)', 'O(n²)', 'O(log n)'],
      correct: 2,
      explanation: 'Quicksort degrades to O(n²) in the worst case, e.g., when the pivot is always the smallest/largest element.',
      difficulty: 'medium',
    },
    {
      id: 'tech_04',
      question: 'In a Binary Search Tree (BST), where is the smallest element located?',
      options: ['Root', 'Rightmost node', 'Leftmost node', 'It depends on insertion order'],
      correct: 2,
      explanation: 'In a BST, the leftmost node (traversed by going left from root every time) holds the minimum value.',
      difficulty: 'easy',
    },
    {
      id: 'tech_05',
      question: 'Which of the following sorting algorithms is stable?',
      options: ['Quick Sort', 'Heap Sort', 'Merge Sort', 'Selection Sort'],
      correct: 2,
      explanation: 'Merge Sort is a stable sorting algorithm — equal elements maintain their relative order.',
      difficulty: 'medium',
    },
    {
      id: 'tech_06',
      question: 'What does SQL "GROUP BY" clause do?',
      options: ['Filters rows', 'Sorts results', 'Aggregates rows with same values', 'Joins two tables'],
      correct: 2,
      explanation: 'GROUP BY groups rows that share the same values into summary rows, typically used with aggregate functions like COUNT, SUM.',
      difficulty: 'easy',
    },
    {
      id: 'tech_07',
      question: 'What is a deadlock in Operating Systems?',
      options: ['A process using 100% CPU', 'Two or more processes waiting indefinitely for resources held by each other', 'An infinite loop', 'Memory overflow'],
      correct: 1,
      explanation: 'A deadlock occurs when a set of processes are each waiting for a resource held by another, causing circular waiting.',
      difficulty: 'medium',
    },
    {
      id: 'tech_08',
      question: 'Which HTTP status code means "Not Found"?',
      options: ['200', '301', '403', '404'],
      correct: 3,
      explanation: '404 Not Found means the server cannot locate the requested resource.',
      difficulty: 'easy',
    },
    {
      id: 'tech_09',
      question: 'What is the space complexity of a recursive Fibonacci function (without memoization)?',
      options: ['O(1)', 'O(n)', 'O(log n)', 'O(n²)'],
      correct: 1,
      explanation: 'The call stack depth grows to O(n) for fib(n), giving O(n) space complexity.',
      difficulty: 'hard',
    },
    {
      id: 'tech_10',
      question: 'Which principle does OOP\'s encapsulation serve?',
      options: ['Code reuse', 'Hiding internal details and exposing only what is necessary', 'Multiple inheritance', 'Compile-time polymorphism'],
      correct: 1,
      explanation: 'Encapsulation bundles data and methods, hiding internal implementation from the outside world.',
      difficulty: 'easy',
    },
    {
      id: 'tech_11',
      question: 'What is the Big-O notation for accessing an element in a Hash Table (average case)?',
      options: ['O(n)', 'O(log n)', 'O(1)', 'O(n²)'],
      correct: 2,
      explanation: 'Hash tables provide O(1) average-case lookup by computing the index directly from the key.',
      difficulty: 'easy',
    },
    {
      id: 'tech_12',
      question: 'In which traversal does a tree visit: Left → Root → Right?',
      options: ['Pre-order', 'Post-order', 'In-order', 'Level-order'],
      correct: 2,
      explanation: 'In-order traversal (Left, Root, Right) of a BST gives nodes in sorted ascending order.',
      difficulty: 'medium',
    },
    {
      id: 'tech_13',
      question: 'What does the "volatile" keyword do in Java/C?',
      options: ['Makes a variable constant', 'Prevents garbage collection', 'Tells the compiler not to cache the variable\'s value', 'Marks a method as thread-safe'],
      correct: 2,
      explanation: 'volatile tells the compiler to always read the variable from main memory, not CPU cache — important in multithreading.',
      difficulty: 'hard',
    },
    {
      id: 'tech_14',
      question: 'Which normal form eliminates transitive dependencies?',
      options: ['1NF', '2NF', '3NF', 'BCNF'],
      correct: 2,
      explanation: '3NF (Third Normal Form) eliminates transitive functional dependencies (non-key attributes depending on other non-key attributes).',
      difficulty: 'hard',
    },
    {
      id: 'tech_15',
      question: 'What is the output of: print(type(1/2)) in Python 3?',
      options: ["<class 'int'>", "<class 'float'>", "<class 'double'>", 'Error'],
      correct: 1,
      explanation: 'In Python 3, the / operator always returns a float. 1/2 = 0.5, type is float.',
      difficulty: 'easy',
    },
    {
      id: 'tech_16',
      question: 'What does DFS stand for in graph traversal?',
      options: ['Data Flow Search', 'Depth-First Search', 'Direct File System', 'Dynamic Fetch Sequence'],
      correct: 1,
      explanation: 'DFS — Depth-First Search — explores as far as possible along each branch before backtracking.',
      difficulty: 'easy',
    },
    {
      id: 'tech_17',
      question: 'Which data structure is best for implementing a priority queue?',
      options: ['Array', 'Linked List', 'Heap', 'Stack'],
      correct: 2,
      explanation: 'A Heap (Min-Heap or Max-Heap) allows O(log n) insertion and O(1) access to the minimum/maximum element, ideal for priority queues.',
      difficulty: 'medium',
    },
    {
      id: 'tech_18',
      question: 'What is the result of: 5 & 3 in binary?',
      options: ['1', '7', '6', '15'],
      correct: 0,
      explanation: '5 = 101, 3 = 011. Bitwise AND: 101 & 011 = 001 = 1.',
      difficulty: 'medium',
    },
    {
      id: 'tech_19',
      question: 'Which algorithm is used to find the shortest path between nodes in a weighted graph?',
      options: ['BFS', 'DFS', 'Dijkstra\'s', 'Kruskal\'s'],
      correct: 2,
      explanation: 'Dijkstra\'s algorithm finds the shortest paths from a source node to all other nodes in a weighted graph.',
      difficulty: 'medium',
    },
    {
      id: 'tech_20',
      question: 'What is a REST API?',
      options: ['A database design pattern', 'An architectural style for networked applications using stateless HTTP communication', 'A JavaScript framework', 'A server-side rendering technique'],
      correct: 1,
      explanation: 'REST (Representational State Transfer) is an architectural style that uses HTTP methods (GET, POST, PUT, DELETE) for stateless communication.',
      difficulty: 'easy',
    },
  ],

  /* ══════════════════════════════════════════════
     ROUND 3: HR ROUND
  ══════════════════════════════════════════════ */
  hr: [
    {
      id: 'hr_01',
      question: 'Tell me about yourself. What is the BEST structure for answering this question?',
      options: [
        'Start from childhood and cover everything in detail',
        'Present → Past → Future: current role/skills, relevant experience, and career goals',
        'Talk only about your personal life and hobbies',
        'Recite your resume word for word'
      ],
      correct: 1,
      explanation: 'The Present → Past → Future structure is clear, concise, and shows career alignment.',
      difficulty: 'easy',
    },
    {
      id: 'hr_02',
      question: 'You notice your team lead made a mistake in a client presentation. What do you do?',
      options: [
        'Correct them publicly in front of the client',
        'Stay quiet — it\'s not your responsibility',
        'Privately inform your lead after or during a break',
        'Email the mistake to management immediately'
      ],
      correct: 2,
      explanation: 'Professional environments require tactful communication. Privately informing shows respect and problem-solving.',
      difficulty: 'medium',
    },
    {
      id: 'hr_03',
      question: 'What is your greatest weakness? Which answer best follows the STAR method?',
      options: [
        '"I have no weaknesses"',
        '"I work too hard — I\'m a perfectionist"',
        '"I used to struggle with public speaking; I joined a debate club and now lead team stand-ups"',
        '"I am bad at everything related to databases"'
      ],
      correct: 2,
      explanation: 'A genuine weakness + concrete steps taken to improve it shows self-awareness and growth mindset.',
      difficulty: 'medium',
    },
    {
      id: 'hr_04',
      question: 'Why do you want to join this company?',
      options: [
        '"Because you are paying more than others"',
        '"Because I need a job urgently"',
        '"Your company\'s work on AI-driven sustainability aligns with my skills and passion for impactful engineering"',
        '"My friend already works here"'
      ],
      correct: 2,
      explanation: 'Answers that align personal skills with company values and mission show genuine interest.',
      difficulty: 'easy',
    },
    {
      id: 'hr_05',
      question: 'A colleague takes credit for your work. How do you handle it?',
      options: [
        'Confront them angrily in the open office',
        'Say nothing and sulk',
        'Discuss it calmly in private, then document your contributions going forward',
        'Complain to everyone on the team'
      ],
      correct: 2,
      explanation: 'Calm private communication followed by documentation protects you professionally and maintains workplace harmony.',
      difficulty: 'medium',
    },
    {
      id: 'hr_06',
      question: 'Where do you see yourself in 5 years?',
      options: [
        '"In your position, managing this company"',
        '"Probably at a different company with higher pay"',
        '"Growing into a senior engineering role, contributing to large-scale systems while mentoring juniors"',
        '"I don\'t think that far ahead"'
      ],
      correct: 2,
      explanation: 'Showing growth ambition aligned with the role demonstrates long-term thinking and fit.',
      difficulty: 'easy',
    },
    {
      id: 'hr_07',
      question: 'You are given a task with an unclear deadline. What do you do?',
      options: [
        'Start immediately and guess the deadline',
        'Wait and hope someone clarifies it eventually',
        'Proactively ask for clarification and set a tentative timeline',
        'Submit whatever you have by end of day regardless'
      ],
      correct: 2,
      explanation: 'Proactively seeking clarity shows ownership, communication skills, and prevents rework.',
      difficulty: 'medium',
    },
    {
      id: 'hr_08',
      question: 'How do you handle working under pressure or tight deadlines?',
      options: [
        'I panic but push through',
        'I ask to extend the deadline',
        'I prioritize tasks, break work into chunks, and communicate progress proactively',
        'I work 24 hours straight without breaks'
      ],
      correct: 2,
      explanation: 'Structured prioritization + clear communication is the professional response to high-pressure situations.',
      difficulty: 'easy',
    },
    {
      id: 'hr_09',
      question: 'What motivates you the most at work?',
      options: [
        'Salary increments only',
        'Solving challenging problems and seeing the measurable impact of my work',
        'Leaving early',
        'Avoiding difficult tasks'
      ],
      correct: 1,
      explanation: 'Intrinsic motivation tied to problem-solving and impact aligns with high-performing engineering cultures.',
      difficulty: 'easy',
    },
    {
      id: 'hr_10',
      question: 'You disagree with a decision made by your manager. What is the best course of action?',
      options: [
        'Refuse to follow the decision',
        'Follow it blindly without question',
        'Request a private meeting, share your perspective with data, then respect the final call',
        'Post about it on LinkedIn'
      ],
      correct: 2,
      explanation: 'Respectfully voicing concerns privately with supporting data shows maturity and collaborative thinking.',
      difficulty: 'medium',
    },
    {
      id: 'hr_11',
      question: 'Describe a situation where you failed. What is the ideal approach?',
      options: [
        '"I have never failed at anything"',
        'Describe a serious failure and blame your team',
        'Describe a failure, what you learned, and what you changed as a result',
        'Avoid answering the question'
      ],
      correct: 2,
      explanation: 'Failure + Learning + Change shows accountability and growth mindset — traits highly valued by recruiters.',
      difficulty: 'medium',
    },
    {
      id: 'hr_12',
      question: 'Do you prefer working alone or in a team?',
      options: [
        '"I only work well alone"',
        '"I only enjoy team work"',
        '"I am comfortable with both — I can collaborate effectively and also focus independently when needed"',
        '"It depends on my mood"'
      ],
      correct: 2,
      explanation: 'Demonstrating flexibility shows adaptability, which is critical in modern agile work environments.',
      difficulty: 'easy',
    },
    {
      id: 'hr_13',
      question: 'How do you prioritize tasks when everything seems urgent?',
      options: [
        'Do them in random order',
        'Work on the easiest ones first',
        'Use frameworks like Eisenhower Matrix or MoSCoW to rank by impact and urgency',
        'Ask your manager to do them for you'
      ],
      correct: 2,
      explanation: 'Structured prioritization frameworks demonstrate organizational maturity and efficiency.',
      difficulty: 'medium',
    },
    {
      id: 'hr_14',
      question: 'A client is unhappy with the deliverable. How do you respond?',
      options: [
        'Defend your work aggressively',
        'Apologize and promise to fix everything immediately without understanding the issue',
        'Listen actively, acknowledge concerns, clarify expectations, and propose a corrective plan',
        'Escalate immediately to your manager without addressing the client'
      ],
      correct: 2,
      explanation: 'Active listening + acknowledgement + clear corrective action is the professional client management approach.',
      difficulty: 'hard',
    },
    {
      id: 'hr_15',
      question: 'What is the STAR method used for in interviews?',
      options: [
        'Rating your performance on a 5-star scale',
        'Structuring behavioral answers: Situation, Task, Action, Result',
        'Scoring technical knowledge',
        'Describing your career goals'
      ],
      correct: 1,
      explanation: 'STAR (Situation, Task, Action, Result) is a widely used framework for answering behavioral interview questions with concrete examples.',
      difficulty: 'easy',
    },
  ],

  /* ══════════════════════════════════════════════
     ROUND 4: CODING ROUND (Output / Logic Tracing)
  ══════════════════════════════════════════════ */
  coding: [
    {
      id: 'code_01',
      question: 'What is the output of this Python code?\n\n```python\ndef mystery(n):\n    if n <= 0: return 0\n    return n + mystery(n - 1)\n\nprint(mystery(5))\n```',
      options: ['10', '15', '5', '25'],
      correct: 1,
      explanation: 'This is a recursive sum: mystery(5) = 5+4+3+2+1+0 = 15.',
      difficulty: 'easy',
      isCode: true,
    },
    {
      id: 'code_02',
      question: 'What does this JavaScript snippet print?\n\n```javascript\nconst arr = [1, 2, 3, 4, 5];\nconst result = arr.filter(x => x % 2 === 0).map(x => x * 3);\nconsole.log(result);\n```',
      options: ['[2, 4]', '[6, 12]', '[1, 3, 5]', '[3, 9, 15]'],
      correct: 1,
      explanation: 'filter keeps even numbers [2, 4]. map multiplies each by 3 → [6, 12].',
      difficulty: 'medium',
      isCode: true,
    },
    {
      id: 'code_03',
      question: 'What is the output?\n\n```python\nx = [1, 2, 3]\ny = x\ny.append(4)\nprint(x)\n```',
      options: ['[1, 2, 3]', '[1, 2, 3, 4]', 'Error', '[4]'],
      correct: 1,
      explanation: 'In Python, y = x creates a reference, not a copy. Both x and y point to the same list object, so appending to y also modifies x.',
      difficulty: 'medium',
      isCode: true,
    },
    {
      id: 'code_04',
      question: 'What does this function return for input 6?\n\n```javascript\nfunction check(n) {\n  for(let i = 2; i <= Math.sqrt(n); i++)\n    if(n % i === 0) return false;\n  return n > 1;\n}\n```',
      options: ['true', 'false', 'undefined', '0'],
      correct: 1,
      explanation: '6 is divisible by 2 (6%2=0), so the loop returns false immediately. 6 is not prime.',
      difficulty: 'medium',
      isCode: true,
    },
    {
      id: 'code_05',
      question: 'What is the time complexity of this code?\n\n```python\nfor i in range(n):\n    for j in range(i, n):\n        print(i, j)\n```',
      options: ['O(n)', 'O(n log n)', 'O(n²)', 'O(2n)'],
      correct: 2,
      explanation: 'Outer loop runs n times, inner loop runs n-i times. Total iterations = n+(n-1)+...+1 = n(n+1)/2 = O(n²).',
      difficulty: 'medium',
      isCode: true,
    },
    {
      id: 'code_06',
      question: 'What is the output?\n\n```python\nd = {"a": 1, "b": 2, "c": 3}\nprint(sum(d.values()))\n```',
      options: ['Error', '"abc"', '6', '3'],
      correct: 2,
      explanation: 'd.values() gives dict_values([1, 2, 3]). sum([1,2,3]) = 6.',
      difficulty: 'easy',
      isCode: true,
    },
    {
      id: 'code_07',
      question: 'Which data structure does this pseudocode implement?\n\n```\npush(x): add x to top\npop(): remove from top\npeek(): return top without removing\n```',
      options: ['Queue', 'Stack', 'Linked List', 'Deque'],
      correct: 1,
      explanation: 'push/pop/peek operating on the "top" is the classic Stack (LIFO) interface.',
      difficulty: 'easy',
      isCode: true,
    },
    {
      id: 'code_08',
      question: 'What is the output of this code?\n\n```javascript\nlet x = 0;\nfor(let i = 1; i <= 5; i++) {\n  x += i;\n}\nconsole.log(x);\n```',
      options: ['10', '15', '5', '25'],
      correct: 1,
      explanation: 'x accumulates: 1+2+3+4+5 = 15.',
      difficulty: 'easy',
      isCode: true,
    },
    {
      id: 'code_09',
      question: 'What is wrong with this code?\n\n```python\ndef divide(a, b):\n    return a / b\n\ndivide(10, 0)\n```',
      options: ['Syntax Error', 'ZeroDivisionError', 'Returns infinity', 'Returns 0'],
      correct: 1,
      explanation: 'Python raises a ZeroDivisionError when dividing by zero. This should be handled with a try/except block.',
      difficulty: 'easy',
      isCode: true,
    },
    {
      id: 'code_10',
      question: 'What does this SQL query return?\n\n```sql\nSELECT COUNT(*) FROM students\nWHERE score > 75\nGROUP BY department;\n```',
      options: [
        'Total number of students',
        'Count of students scoring above 75, per department',
        'Department names only',
        'Average score per department'
      ],
      correct: 1,
      explanation: 'GROUP BY department groups results per department. COUNT(*) counts rows in each group where score > 75.',
      difficulty: 'medium',
      isCode: true,
    },
    {
      id: 'code_11',
      question: 'What is the output?\n\n```python\nprint(bool(""), bool("hello"), bool(0), bool(1))\n```',
      options: [
        'False True False True',
        'True True False True',
        'False False False True',
        'False True True True'
      ],
      correct: 0,
      explanation: 'Empty string "" and 0 are falsy in Python. "hello" and 1 are truthy. Output: False True False True.',
      difficulty: 'medium',
      isCode: true,
    },
    {
      id: 'code_12',
      question: 'What will this code print?\n\n```javascript\nconst nums = [3, 1, 4, 1, 5];\nnums.sort();\nconsole.log(nums[0]);\n```',
      options: ['1', '3', 'undefined', '5'],
      correct: 0,
      explanation: 'Array.sort() without a comparator sorts lexicographically. Sorted: [1,1,3,4,5]. First element is 1.',
      difficulty: 'hard',
      isCode: true,
    },
  ],
};

export const ROUND_CONFIG = [
  {
    id: 'aptitude',
    label: 'Aptitude',
    icon: '🔢',
    color: 'blue',
    gradient: 'from-blue-500 to-cyan-500',
    bgLight: 'bg-blue-50 dark:bg-blue-900/20',
    textColor: 'text-blue-600 dark:text-blue-400',
    border: 'border-blue-200 dark:border-blue-700',
    description: 'Quantitative reasoning, logical puzzles, and analytical thinking',
    questionCount: 10,
    timePerQuestion: 60, // seconds
    xpPerCorrect: 10,
  },
  {
    id: 'technical',
    label: 'Technical',
    icon: '⚙️',
    color: 'emerald',
    gradient: 'from-emerald-500 to-teal-500',
    bgLight: 'bg-emerald-50 dark:bg-emerald-900/20',
    textColor: 'text-emerald-600 dark:text-emerald-400',
    border: 'border-emerald-200 dark:border-emerald-700',
    description: 'Data Structures, Algorithms, OS, DBMS, System Design',
    questionCount: 10,
    timePerQuestion: 90,
    xpPerCorrect: 15,
  },
  {
    id: 'hr',
    label: 'HR Round',
    icon: '🤝',
    color: 'purple',
    gradient: 'from-purple-500 to-pink-500',
    bgLight: 'bg-purple-50 dark:bg-purple-900/20',
    textColor: 'text-purple-600 dark:text-purple-400',
    border: 'border-purple-200 dark:border-purple-700',
    description: 'Behavioral questions, situational judgment, and soft skills',
    questionCount: 8,
    timePerQuestion: 75,
    xpPerCorrect: 12,
  },
  {
    id: 'coding',
    label: 'Coding',
    icon: '💻',
    color: 'orange',
    gradient: 'from-orange-500 to-red-500',
    bgLight: 'bg-orange-50 dark:bg-orange-900/20',
    textColor: 'text-orange-600 dark:text-orange-400',
    border: 'border-orange-200 dark:border-orange-700',
    description: 'Code output tracing, logic analysis, and pseudocode',
    questionCount: 8,
    timePerQuestion: 120,
    xpPerCorrect: 20,
  },
];
